// Code generated by Kitex v0.5.2. DO NOT EDIT.

package videoservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	video "github.com/dawnzzz/MicroTiktok/kitex_gen/video"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Feed(ctx context.Context, req *video.FeedRequest, callOptions ...callopt.Option) (r *video.FeedResponse, err error)
	PublishVideo(ctx context.Context, req *video.PublishRequest, callOptions ...callopt.Option) (r *video.PublishResponse, err error)
	GetPublishedVideoList(ctx context.Context, req *video.GetPublishedListRequest, callOptions ...callopt.Option) (r *video.GetPublishedListResponse, err error)
	GetFavoriteVideoList(ctx context.Context, req *video.GetFavoriteListRequest, callOptions ...callopt.Option) (r *video.GetFavoriteListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) Feed(ctx context.Context, req *video.FeedRequest, callOptions ...callopt.Option) (r *video.FeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Feed(ctx, req)
}

func (p *kVideoServiceClient) PublishVideo(ctx context.Context, req *video.PublishRequest, callOptions ...callopt.Option) (r *video.PublishResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishVideo(ctx, req)
}

func (p *kVideoServiceClient) GetPublishedVideoList(ctx context.Context, req *video.GetPublishedListRequest, callOptions ...callopt.Option) (r *video.GetPublishedListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPublishedVideoList(ctx, req)
}

func (p *kVideoServiceClient) GetFavoriteVideoList(ctx context.Context, req *video.GetFavoriteListRequest, callOptions ...callopt.Option) (r *video.GetFavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFavoriteVideoList(ctx, req)
}
