// Code generated by Kitex v0.5.2. DO NOT EDIT.

package authenticationservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	authentication "github.com/dawnzzz/MicroTiktok/kitex_gen/authentication"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GenerateToken(ctx context.Context, req *authentication.GenerateTokenRequest, callOptions ...callopt.Option) (r *authentication.GenerateTokenResponse, err error)
	CheckToken(ctx context.Context, req *authentication.CheckTokenRequest, callOptions ...callopt.Option) (r *authentication.CheckTokenResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAuthenticationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAuthenticationServiceClient struct {
	*kClient
}

func (p *kAuthenticationServiceClient) GenerateToken(ctx context.Context, req *authentication.GenerateTokenRequest, callOptions ...callopt.Option) (r *authentication.GenerateTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateToken(ctx, req)
}

func (p *kAuthenticationServiceClient) CheckToken(ctx context.Context, req *authentication.CheckTokenRequest, callOptions ...callopt.Option) (r *authentication.CheckTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckToken(ctx, req)
}
