// Code generated by Kitex v0.5.2. DO NOT EDIT.

package favoriteservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	favorite "github.com/dawnzzz/MicroTiktok/kitex_gen/favorite"
)

func serviceInfo() *kitex.ServiceInfo {
	return favoriteServiceServiceInfo
}

var favoriteServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "FavoriteService"
	handlerType := (*favorite.FavoriteService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Favorite":             kitex.NewMethodInfo(favoriteHandler, newFavoriteServiceFavoriteArgs, newFavoriteServiceFavoriteResult, false),
		"FavoriteCancel":       kitex.NewMethodInfo(favoriteCancelHandler, newFavoriteServiceFavoriteCancelArgs, newFavoriteServiceFavoriteCancelResult, false),
		"GetFavoriteVideoList": kitex.NewMethodInfo(getFavoriteVideoListHandler, newFavoriteServiceGetFavoriteVideoListArgs, newFavoriteServiceGetFavoriteVideoListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "favorite",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.2",
		Extra:           extra,
	}
	return svcInfo
}

func favoriteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceFavoriteArgs)
	realResult := result.(*favorite.FavoriteServiceFavoriteResult)
	success, err := handler.(favorite.FavoriteService).Favorite(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteServiceFavoriteArgs() interface{} {
	return favorite.NewFavoriteServiceFavoriteArgs()
}

func newFavoriteServiceFavoriteResult() interface{} {
	return favorite.NewFavoriteServiceFavoriteResult()
}

func favoriteCancelHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceFavoriteCancelArgs)
	realResult := result.(*favorite.FavoriteServiceFavoriteCancelResult)
	success, err := handler.(favorite.FavoriteService).FavoriteCancel(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteServiceFavoriteCancelArgs() interface{} {
	return favorite.NewFavoriteServiceFavoriteCancelArgs()
}

func newFavoriteServiceFavoriteCancelResult() interface{} {
	return favorite.NewFavoriteServiceFavoriteCancelResult()
}

func getFavoriteVideoListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceGetFavoriteVideoListArgs)
	realResult := result.(*favorite.FavoriteServiceGetFavoriteVideoListResult)
	success, err := handler.(favorite.FavoriteService).GetFavoriteVideoList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteServiceGetFavoriteVideoListArgs() interface{} {
	return favorite.NewFavoriteServiceGetFavoriteVideoListArgs()
}

func newFavoriteServiceGetFavoriteVideoListResult() interface{} {
	return favorite.NewFavoriteServiceGetFavoriteVideoListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Favorite(ctx context.Context, req *favorite.FavoriteRequest) (r *favorite.FavoriteResponse, err error) {
	var _args favorite.FavoriteServiceFavoriteArgs
	_args.Req = req
	var _result favorite.FavoriteServiceFavoriteResult
	if err = p.c.Call(ctx, "Favorite", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FavoriteCancel(ctx context.Context, req *favorite.FavoriteCancelRequest) (r *favorite.FavoriteCancelResponse, err error) {
	var _args favorite.FavoriteServiceFavoriteCancelArgs
	_args.Req = req
	var _result favorite.FavoriteServiceFavoriteCancelResult
	if err = p.c.Call(ctx, "FavoriteCancel", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFavoriteVideoList(ctx context.Context, req *favorite.GetFavoriteVideoListRequest) (r *favorite.GetFavoriteVideoListResponse, err error) {
	var _args favorite.FavoriteServiceGetFavoriteVideoListArgs
	_args.Req = req
	var _result favorite.FavoriteServiceGetFavoriteVideoListResult
	if err = p.c.Call(ctx, "GetFavoriteVideoList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
