// Code generated by Kitex v0.5.2. DO NOT EDIT.

package commentservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	comment "github.com/dawnzzz/MicroTiktok/kitex_gen/comment"
)

func serviceInfo() *kitex.ServiceInfo {
	return commentServiceServiceInfo
}

var commentServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "CommentService"
	handlerType := (*comment.CommentService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Comment":        kitex.NewMethodInfo(commentHandler, newCommentServiceCommentArgs, newCommentServiceCommentResult, false),
		"CommentDelete":  kitex.NewMethodInfo(commentDeleteHandler, newCommentServiceCommentDeleteArgs, newCommentServiceCommentDeleteResult, false),
		"GetCommentList": kitex.NewMethodInfo(getCommentListHandler, newCommentServiceGetCommentListArgs, newCommentServiceGetCommentListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "comment",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.2",
		Extra:           extra,
	}
	return svcInfo
}

func commentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*comment.CommentServiceCommentArgs)
	realResult := result.(*comment.CommentServiceCommentResult)
	success, err := handler.(comment.CommentService).Comment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCommentServiceCommentArgs() interface{} {
	return comment.NewCommentServiceCommentArgs()
}

func newCommentServiceCommentResult() interface{} {
	return comment.NewCommentServiceCommentResult()
}

func commentDeleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*comment.CommentServiceCommentDeleteArgs)
	realResult := result.(*comment.CommentServiceCommentDeleteResult)
	success, err := handler.(comment.CommentService).CommentDelete(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCommentServiceCommentDeleteArgs() interface{} {
	return comment.NewCommentServiceCommentDeleteArgs()
}

func newCommentServiceCommentDeleteResult() interface{} {
	return comment.NewCommentServiceCommentDeleteResult()
}

func getCommentListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*comment.CommentServiceGetCommentListArgs)
	realResult := result.(*comment.CommentServiceGetCommentListResult)
	success, err := handler.(comment.CommentService).GetCommentList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCommentServiceGetCommentListArgs() interface{} {
	return comment.NewCommentServiceGetCommentListArgs()
}

func newCommentServiceGetCommentListResult() interface{} {
	return comment.NewCommentServiceGetCommentListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Comment(ctx context.Context, req *comment.CommentRequest) (r *comment.CommentResponse, err error) {
	var _args comment.CommentServiceCommentArgs
	_args.Req = req
	var _result comment.CommentServiceCommentResult
	if err = p.c.Call(ctx, "Comment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommentDelete(ctx context.Context, req *comment.CommentDeleteRequest) (r *comment.CommentDeleteResponse, err error) {
	var _args comment.CommentServiceCommentDeleteArgs
	_args.Req = req
	var _result comment.CommentServiceCommentDeleteResult
	if err = p.c.Call(ctx, "CommentDelete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCommentList(ctx context.Context, req *comment.GetCommentListRequest) (r *comment.GetCommentListResponse, err error) {
	var _args comment.CommentServiceGetCommentListArgs
	_args.Req = req
	var _result comment.CommentServiceGetCommentListResult
	if err = p.c.Call(ctx, "GetCommentList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
